"""
Reproducible notebook export (Phase 11 differentiator #6).

Any pivot/chat selection exports as a Jupyter .ipynb that reproduces the EXACT
governed Cube query (show-your-work for auditors/analysts): the query JSON, a
runnable snippet that posts it to the Cube REST API, and the locale settings.
Deterministic — the notebook reruns the same governed query, never re-derives.
"""
from __future__ import annotations

from typing import Annotated, Any

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, ConfigDict, Field

from services.api_gateway.app.auth import Principal, current_principal

router = APIRouter(prefix="/v1/notebook", tags=["notebook"])


class NotebookRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")
    project_id: str
    title: str = "Insights Navigator export"
    measures: list[str] = Field(default_factory=list)
    dimensions: list[str] = Field(default_factory=list)
    time_dimension: str | None = None
    granularity: str | None = None
    filters: list[dict[str, Any]] = Field(default_factory=list)
    order: dict[str, str] = Field(default_factory=dict)
    limit: int | None = None


def _md(*lines: str) -> dict[str, Any]:
    return {"cell_type": "markdown", "metadata": {}, "source": [l + "\n" for l in lines]}


def _code(*lines: str) -> dict[str, Any]:
    return {"cell_type": "code", "metadata": {}, "execution_count": None, "outputs": [],
            "source": [l + "\n" for l in lines]}


@router.post("")
def export_notebook(
    req: NotebookRequest,
    principal: Annotated[Principal, Depends(current_principal)],
) -> dict[str, Any]:
    """Return a .ipynb (Jupyter notebook JSON) reproducing the governed query."""
    from services.api_gateway.app.cube_query_service import UnknownField, run_spec
    from services.api_gateway.app.projects import get_project

    p = get_project(req.project_id)
    if p is None or p.tenant_id != principal.tenant_id:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "project not found")

    # Build + validate the query (run it so the notebook can embed sample rows).
    try:
        columns, rows, query = run_spec(
            tenant_id=principal.tenant_id, project_id=req.project_id,
            measures=req.measures, dimensions=req.dimensions,
            time_dimension=req.time_dimension, granularity=req.granularity,
            filters=req.filters, order=req.order, limit=req.limit,
        )
    except UnknownField as e:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, str(e)) from e

    import json as _json

    query_json = _json.dumps(query, indent=2)
    sample = _json.dumps({"columns": columns, "rows": rows[:20]}, indent=2)

    cells = [
        _md(f"# {req.title}",
            "",
            f"*Project `{p.name}` · locale {p.locale_default} · generated by Insights Navigator V2.0*",
            "",
            "This notebook reproduces a **governed Cube query**. The semantic layer",
            "compiles deterministic SQL from human-confirmed definitions — the numbers",
            "below are not re-derived here, they are the exact query the platform ran."),
        _md("## The governed query"),
        _code("CUBE_QUERY = " + query_json),
        _md("## Run it against your Cube deployment",
            "Set `CUBE_API_URL` and a Cube API token (mint one server-side; it carries",
            "your `tenant_id` + `project_id` security context)."),
        _code(
            "import os, requests, pandas as pd",
            "CUBE_API_URL = os.environ.get('CUBE_API_URL', 'https://<your-cube>/cubejs-api/v1')",
            "CUBE_TOKEN = os.environ['CUBE_TOKEN']  # JWT with {tenant_id, project_id}",
            "r = requests.post(f'{CUBE_API_URL}/load',",
            "                  json={'query': CUBE_QUERY},",
            "                  headers={'Authorization': CUBE_TOKEN})",
            "r.raise_for_status()",
            "df = pd.json_normalize(r.json()['data'])",
            "df",
        ),
        _md("## Sample result captured at export time"),
        _code("SAMPLE = " + sample, "import pandas as pd", "pd.DataFrame(SAMPLE['rows'], columns=SAMPLE['columns'])"),
    ]

    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"},
            "insnav": {"project_id": req.project_id, "tenant_id": principal.tenant_id},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
